### PR TITLE
Bring dd4hep, acts, and eigen into container

### PR DESCRIPTION
**Pull request by tomeichlersmith**
I am adding a new package to the container, here are the details.

### What new packages does this PR add to the development container?
- dd4hep
- eigen
- acts

## Check List
- [x] I successfully built the container using docker
```
# outline of container build instructions
cd docker
git checkout my-updates
docker build . -t ldmx/local:temp-tag
```
- [x] I was able to build ldmx-sw/trunk using this new container build
```
# outline of build instructions
ldmx use local temp-tag
cd ldmx-sw
mkdir build
cd build
ldmx cmake ..
ldmx make install
```
- [ ] I was able to test run a small simulation and reconstruction inside this container
```
# outline of test instructions
cd $LDMX_BASE
ldmx run_test
for c in `ls ldmx-sw/*/test/*.py`; ldmx fire $c; done
```
- [ ] I was able to successfully use the new packages. Explain what you did to test them below:
```
# planning to test by compiling ldmx-sw/dd4hep-dev branch
cd ldmx-sw
git fetch
git checkout dd4hep-dev
git submodule update --init
cd cmake
git checkout dd4hep-dev
ldmx cmake -B build -S .
cd build
ldmx make
```

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
@omar-moreno @pbutti I have built a container with ACTS v14.1.0 and DD4hep v01-18 that is not conflicting with `main`. This has been pushed to `ldmx/dev:pr-dd4hep-acts`. Could y'all try to use it?

I tried to build the `dd4hep-dev` branch of ldmx-sw and quickly ran into a compiling error that I did not know how to solve.
```
[ 99%] Building CXX object Detectors/CMakeFiles/Tracker.dir/src/Detectors/DD4hep/Tracker.cxx.o
/export/scratch/users/eichl008/ldmx/ldmx-sw/Detectors/src/Detectors/DD4hep/Tracker.cxx:123:19: error: expected constructor, destructor, or type conversion before '(' token
 DECLARE_DETELEMENT(tracker, create_tracker)
                   ^
Detectors/CMakeFiles/Tracker.dir/build.make:75: recipe for target 'Detectors/CMakeFiles/Tracker.dir/src/Detectors/DD4hep/Tracker.cxx.o' failed
make[2]: *** [Detectors/CMakeFiles/Tracker.dir/src/Detectors/DD4hep/Tracker.cxx.o] Error 1
CMakeFiles/Makefile2:1535: recipe for target 'Detectors/CMakeFiles/Tracker.dir/all' failed
make[1]: *** [Detectors/CMakeFiles/Tracker.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```
This was _after_ fixing the central CMakeLists with [the patch PF linked in slack](https://eicweb.phy.anl.gov/EIC/NPDet/-/commit/b797e0c7a029ce8179168c12f28ba874c6c6aabc?merge_request_iid=194) and applying other patches I recognized. The `git diff` showing what I've done with respect to the `ldmx-sw/dd4hep-dev` branch is below.
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7a5a13b..40b8b9b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,6 +23,13 @@ if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
     message(STATUS "Install directory set to ${CMAKE_INSTALL_PREFIX}")
 endif()
 
+# Force C++17
+if(NOT CMAKE_CXX_STANDARD)
+  set(CMAKE_CXX_STANDARD 17 CACHE STRING "...." FORCE)
+  set(CMAKE_CXX_STANDARD_REQUIRED ON)
+  set(CMAKE_CXX_EXTENSIONS OFF)
+endif()
+
 # If a user is building outside of a Docker or Singularity environment, 
 # warn them. 
 if (NOT EXISTS /.dockerenv AND NOT EXISTS /singularity)
diff --git a/Detectors/CMakeLists.txt b/Detectors/CMakeLists.txt
index 057d019..53eae2a 100644
--- a/Detectors/CMakeLists.txt
+++ b/Detectors/CMakeLists.txt
@@ -22,7 +22,7 @@ file(GLOB SRC_FILES CONFIGURE_DEPENDS
 )
 
 setup_library(module Detectors
-              dependencies DD4hep::DDCore
+              dependencies DD4hep::DDCore Eigen3::Eigen
               sources ${SRC_FILES})
 
 dd4hep_add_plugin(Tracker SOURCES ${PROJECT_SOURCE_DIR}/src/Detectors/DD4hep/*.cxx
diff --git a/cmake b/cmake
index cb4b7c0..7acd65e 160000
--- a/cmake
+++ b/cmake
@@ -1 +1 @@
-Subproject commit cb4b7c0f41747c22c6070cb572626d4e8d7cd457
+Subproject commit 7acd65e54abbae6f20fa31d891ff843e21d9f0ed
```
`cmake` is on its `dd4hep-dev` branch and `Tracking`

**Comment by pbutti** [comment]
Hello @tomeichlersmith,
thank you so much for this! I saw the error few days ago and we made the `tracking_dev` branch where this should be fixed.
The issue should just be a missing include, specifically
`#include "DD4hep/Factories.h"`
that defines the macro. 
 I will test the container right now and let you know!

**Comment by tomeichlersmith** [comment]
It looks like you need a plugin that has not been built into the container:
```
In file included from /export/scratch/users/eichl008/ldmx/ldmx-sw/Tracking/src/Tracking/Sim/TrackingGeometryMaker.cxx:1:0:
/export/scratch/users/eichl008/ldmx/ldmx-sw/Tracking/include/Tracking/Sim/TrackingGeometryMaker.h:21:10: fatal error: Acts/Plugins/DD4hep/ActsExtension.hpp: No such file or directory
 #include "Acts/Plugins/DD4hep/ActsExtension.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
But I have explicitly turned off the DD4hep plugin for ACTS, so
```
> ldmx ls /usr/local/include/Acts/
ActsVersion.hpp  Definitions  Geometry	     Material	 Seeding   TrackFinding  Utilities  Visualization
Clusterization	 EventData    MagneticField  Propagator  Surfaces  TrackFitting  Vertexing
```

**Comment by pbutti** [comment]
Hi Tom, 
Yes, I was about to comment that as I noticed the issue. Since dd4hep is now included, could you activate the Plugin? 
In principle I could avoid using the ActsExtension, but would still be useful to have the plugin active. What I found is that to compile acts with dd4hep included, I had to force the C++17 extensions in the ACTS CMakeLists.

**Comment by tomeichlersmith** [comment]
Okie doke, I can make this work, but it will take some hacking.

Is there potential for getting this cmake patch into mainline ACTS? I don't want to be writing code with code for too long...

**Comment by pbutti** [comment]
Meeting with one of the devs tomorrow for unrelated stuff, but I can bring the problem up, yes. Maybe it's just me that I'm not able to compile it properly XD (I tried only on macOs btw)

**Comment by paulgessinger** [comment]
> Okie doke, I can make this work, but it will take some hacking.
> 
> Is there potential for getting this cmake patch into mainline ACTS? I don't want to be writing code with code for too long...

Maybe I can chime in here. The issue with this is a bit that it's DD4hep dependent. 

We use target specific C++ standard settings like 

```
target_compile_features(
  ActsCore
  PUBLIC cxx_std_17)
```

In principle, it should be sufficient to **build** DD4hep with C++17. My understanding is that this is not correctly preserved through to DD4hep's installed CMake, meaning that if the global `CMAKE_CXX_STANDARD` is not set, it will break.

We're hesitant to add setting global `CMAKE_CXX_STANDARD=17`, since we don't think that's a good practice for *library*.

**Comment by tomeichlersmith** [comment]
Thank you for the extra context @paulgessinger ! :100: I appreciate you taking the time and the current solution is working for us, so I think we wiill be ok.

**Pull request merged**
