### PR TITLE
unify derivatives into the development container

### PR DESCRIPTION
**Pull request by tomeichlersmith**
I am updating the base development container, here are the details.

## Description
It seems like most developers only need a few more python packages in order to be able to utilize the container. With this in mind, it will be a lot easier to maintain the container ecosystem with only one development container to work off of. This new development container changes a few things:
- Update cmake to version 3.17 to accomodate the cmake updates for ldmx-sw as well as the ROOT cmake updates
- Update ROOT to version 6.22 so that we can have PyROOT built simultaneously for python2 and python3
- Install the following packages in both python2 and python3
   - uproot
   - numpy
   - ~~rootpy : change `XDG_CONFIG_HOME` and `XDG_CACHE_HOME` to locations inside of `LDMX_BASE` so that they persist between runs of the container~~
   - matplotlib
   - xgboost
   - sklearn
- Import some SSL certificates that we want the container to trust
    - Any SSL certificates in the `certs` directory are imported into the container so that the container can download data from servers signed with those certificates. Context: #27 .

For testing purposes, I am using the tag `unification` on docker hub until we can verify that this container doesn't break anyone's workflow.

## Still TODO
- [x] Remove the derivaties directory and the derivatives building action
- [x] Document updates to container
- [ ] Test the packages for functionality
- [x] Successfully `run_test` with this container
- [x] Successfully run all the test configs with this container

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
If I have requested your review, I remember helping you figure out a specific workflow using the container in the past. I want to make sure this doesn't break anything for anyone, so please add in your "review" of the container:  i.e. Can you build ldmx-sw? Can you run your normal scripts? Can you use your analysis scripts? Basically, can your workflow _not change_ if you change the container you are using.

To switch to this newer container, you can use a function defined by the environment script:
```
source ldmx-sw/scripts/ldmx-env.sh
ldmx-container-pull dev unification
```

**Comment by tomeichlersmith** [comment]
@jmlazaro25 My initial tests are showing that `rootpy` is **not compatible** with ROOT version 6.22 i.e. `rootpy` depends on `PyROOT` defining `ROOT.module._root` which doesn't exist anymore with the new method ROOT is using to generate the python bindings.

It looks like this issue has been seen before, and it may be left behind. https://github.com/rootpy/rootpy/issues/816

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rootpy/__init__.py", line 31, in <module>
    from .utils import quickroot as QROOT
  File "/deps/cernroot/lib/ROOT/_facade.py", line 121, in _importhook
    return _orig_ihook(name, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/rootpy/utils/quickroot.py", line 15, in <module>
    root_module = ROOT.module._root
AttributeError: 'module' object has no attribute '_root'
```

**Comment by tomeichlersmith** [comment]
Did you start from an empty build directory? The files in your build directory will look like they came from a different computer because they were compiled in a different container. Switching to a new container would mean you have to delete those files.

**Comment by bryngemark** [comment]
Yes, I nuked the build dir.

**Comment by tomeichlersmith** [comment]
After some lengthy googling, I found that `c++: internal compiler error: Killed (program cc1plus)` _may_ be caused by the compiler running out of RAM. On MacOS, this is easier because docker runs inside of a virtual machine that has a limited amount of memory allocated to it. Two potential solutions:
1. Run `make` with less cores so the amount of RAM used at one time is decreased: `make install`
2. Provision more RAM for the docker container. I don't know how to do this, but I'm sure there is an explanation somewhere on docker's docs.

**Comment by bryngemark** [comment]
Update: it works if I don't compile in parallel. So `ldmx make install` works.

**Comment by bryngemark** [comment]
Oh I see, you had suggested that too! Well I can only confirm then :)

**Comment by sophiemiddleton** [comment]
This sounds good to me....let me know when you have it ready for a full review

**Comment by tomeichlersmith** [comment]
Alright, after some surprising bugs that just kept popping up. I was able to get everything working again.

@sophiemiddleton @bryngemark @jmlazaro25 @vdutta Could you all go through your "normal" workflow? Testing various scripts to see if they work. Please "review" this PR and "approve" it if everything works alright. Some reminders:
- New container means totally new build `rm -r build` before rebuilding ldmx-sw so there isn't any cross-contamination
- Get this container with `ldmx-container-pull dev unification`
- Run the python interpreter in the container with `ldmx python` or `ldmx python3`

**Review by bryngemark — APPROVED** [review]
This looks ok with me. My summer student was able to run his analysis code using this container, too.

**Comment by tomeichlersmith** [comment]
@sophiemiddleton @vdutta I would like to get this PR wrapped up by the end of the week. If you are too busy to test the container yourself, please send me (either here or in slack) some `import` commands that you use in your python analyses and any other commands you want to make sure work inside of the container. Thank you.

**Comment by sophiemiddleton** [comment]
Hi Tom,

For the imports at the moment I use matplotlib  and numpy only but uproot would be very useful. I might use sklearn eventually too when we get doing more sophisicated BDT work for the WABs.

I'm busy today so its fine if you just do the basic checks you need to get this through.

Thanks,
Sophie

**Review by sophiemiddleton — APPROVED** [review]

**Review by sophiemiddleton — APPROVED** [review]

**Review by vdutta — APPROVED** [review]

**Pull request merged**
