### PR TITLE
Iss31 - Addition of DD4hep and ACTS

### PR DESCRIPTION
**Pull request by tomeichlersmith**
I am adding DD4hep and ACTS to the container, here are the details.

### What new packages does this PR add to the development container?
- DD4hep
- Boost 1.74 (upgrade from default in Ubuntu repos)
- Eigen 3.8.3 (for ACTS)
- ACTS

### Other Changes
- Move all installation commands into the `Dockerfile` so that caching layers works as expected
- Use `cmake` to both configure and build (means we don't have as many `cd` floating around - less complicated)
- Update extra python package install so that it doesn't require the entrypoint script
- Copy entrypoint script into container last

## Check List
- [x] I successfully built the container using docker
```
# outline of container build instructions
cd docker
git checkout my-updates
docker build . -t ldmx/local:temp-tag
```
- [x] I was able to build ldmx-sw using this new container build
```
# outline of build instructions
ldmx-container-pull local temp-tag
cd ldmx-sw
mkdir build
cd build
ldmx cmake -DBUILD_TESTS=ON ..
ldmx make install
```
- [x] I was able to test run a small simulation and reconstruction inside this container
```
# outline of test instructions
cd $LDMX_BASE
ldmx run_test
for c in `ls ldmx-sw/*/test/*.py`; ldmx fire $c; done
```
- [x] I was able to successfully use the new packages. Explain what you did to test them below:
I "tested" DD4hep by using this container to compile the branch `ldmx-sw/dd4hep-dev`.
~~I have **not** tested ACTS with ldmx-sw because there aren't ACTS components of ldmx-sw right now.~~
@pbutti confirmed that he can compile a version of ldmx-sw that uses ACTS with this container below.

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
@omar-moreno I have a container tagged `ldmx/dev:iss31` that we can play with to see how it works with your updates.
To use this container:
```
source ldmx-sw/scripts/ldmx-env.sh
ldmx-container-pull dev iss31
```
Then you can check your dd4hep stuff.

## Some things I've noticed that may require changes in ldmx-sw
- The test executable is not linking correctly to the other libraries anymore:
```
-- Configuring done
CMake Error at cmake/BuildMacros.cmake:421 (add_executable):
  Target "run_test" links to target "DARK::DetDescr" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:135 (build_test)


CMake Error at cmake/BuildMacros.cmake:421 (add_executable):
  Target "run_test" links to target "DARK::Ecal" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:135 (build_test)


CMake Error at cmake/BuildMacros.cmake:421 (add_executable):
  Target "run_test" links to target "DARK::Conditions" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:135 (build_test)


CMake Error at cmake/BuildMacros.cmake:421 (add_executable):
  Target "run_test" links to target "DD4hep::DDCore" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:135 (build_test)


-- Generating done
```
- There is some odd `cmake` warning about boost:
```
[ WARNING ]: New Boost version may have incorrect or missing dependencies and imported targets
```
- I couldn't run a basic simulation. Did you move where the python modules are installed to?
```
---- LDMXSW: Loading configuration --------
Traceback (most recent call last):
  File "/home/tom/ldmx/ldmx-sw/SimCore/test/basic.py", line 1, in <module>
    from LDMX.Framework import ldmxcfg
ModuleNotFoundError: No module named 'LDMX'
Configuration Error [ConfigureError] : Problem loading python script
  at /home/tom/ldmx/ldmx-sw/Framework/src/Framework/ConfigurePython.cxx:205 in ConfigurePython
```

**Comment by pbutti** [comment]
Hi all, 

I'd like to ask if the ACTS version stored in the docker could be upgraded to a more recent release or to the current acts master. The reason is because some classes in the Acts/Core/Material package have been updated and they are needed for building the tracking geometry. I can still use the old way, but the sooner we update this the better as I'm actively working on the code now. 
Let me know if I can help in some way, but my docker exp is super low, so you might need to guide me a little..

**Comment by tomeichlersmith** [comment]
Hi @pbutti I can pull any branch/tag from the acts code base: https://github.com/acts-project/acts

I would prefer to use a release so that the container can be re-built reliably in the future (if necessary). Does v1.2.1 work for your purposes? v2.0.0? Or is the stuff you need only on master?

**Comment by pbutti** [comment]
Hi @tomeichlersmith , I'm dumb. I just re-checked and I think that *my* fork was outdated and * the ldmx docker* is just fine. Sorry.... 
But yes: in the case you are looking into this and want to update  v1.2.1 should work

**Comment by pbutti** [comment]
@tomeichlersmith ,

thanks a lot for the update. Does this mean that getting iss31 will pick the new acts version or there is something to change in the setup?

**Comment by tomeichlersmith** [comment]
It takes awhile to build, so I will let you know when it successfully
completes and the newer ACTS version is available.

**Comment by tomeichlersmith** [comment]
@pbutti The build completed successfully, so the image on DockerHub tagged `ldmx/dev:iss31` is updated with ACTS version 1.2.1

**Comment by pbutti** [comment]
Hey @tomeichlersmith 
Thank you for this. I'll check it out today. Same procedure to use the docker locally?

**Comment by tomeichlersmith** [comment]
Similar, after `source ldmx-sw/scripts/ldmx-env.sh`, you will need to force the new container to be downloaded. There is a helper bash function for this:
`ldmx-container-pull dev iss31` will pull down the `ldmx/dev:iss31` container even if it exists locally.

**Comment by pbutti** [comment]
Hi @tomeichlersmith ,

i can confirm that I was able to get the newer version of Acts:
[ INFO ]: found Acts version 1.2.1 commit f6ebeb9a2
and compiles fine.

**Pull request merged**
